# -*- coding: utf-8 -*-
"""nota_prevista.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13r2diYsiMbqDAYNHTy0sdp6_v79bSrD6
"""

import numpy as np
from scipy import interpolate

# Número das provas (eixo x)
provas = np.array([1, 2, 3])

# Notas que o aluno tirou (eixo y)
notas = np.array([6, 7, 8])

# Criando uma função para estimar a nota na prova 4
f = interpolate.interp1d(provas, notas, fill_value="extrapolate")

# Previsão para a prova 4
nota_prevista = f(4)

print("Nota prevista na prova 4:", nota_prevista)

"""Se as notas estão subindo de 1 em 1 (de 6 para 7, de 7 para 8), então é razoável prever que a próxima seja 9. O computador fez uma estimativa matemática baseada nos dados anteriores. Isso é útil para analisar desempenho, prever resultados e até montar gráficos com previsões futuras!"""

# Jogos (eixo x)
jogos = np.array([1, 2, 3, 4, 5])

# Gols feitos pelo atacante (eixo y)
gols = np.array([1, 2, 3, 2, 3])

# Criando uma função para estimar os gols no Jogo 6
f = interpolate.interp1d(jogos, gols, fill_value="extrapolate")

# Previsão para o Jogo 6
gols_previstos = f(6)

print("Gols previstos no Jogo 6:", gols_previstos)