# -*- coding: utf-8 -*-
"""scipy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgIqWD8iy7i6E6jKT20Yw5fJjUDoYkZQ
"""

#https://docs.scipy.org/doc/scipy/tutorial/index.html
#!pip install scipy
import scipy

temp_celsius = 20.0
temp_fahrenhiet = (temp_celsius * 9/5) + 32
print(f'{temp_celsius} graus Celsius é equivalente a {temp_fahrenhiet} graus Fahrenhiet.')

from scipy.constants import c

# Velocidade da luz no vacuo em metros por segundo
velocidade_da_luz_m_s = c

# Convertendo para quilometros por segundo
velocidade_da_luz_km_s = velocidade_da_luz_m_s / 1000

# Convertendo para quilometros por hora
velocidade_da_luz_km_h = velocidade_da_luz_km_s * 3600

print("Velocidade da luz no vacuo:")
print("Em metros por segundo:", velocidade_da_luz_m_s)
print("Em quilometros por segundo:", velocidade_da_luz_km_s)
print("Em quilometros por hora:", velocidade_da_luz_km_h)

from scipy.constants import convert_temperature
from numpy import array

convert_temperature(array([20]), 'C', 'F')